# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: network.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='network.proto',
  package='network',
  syntax='proto2',
  serialized_pb=_b('\n\rnetwork.proto\x12\x07network\"\xa0\x02\n\nLayerParam\x12\x13\n\x0binput_shape\x18\t \x03(\r\x12\x14\n\x0coutput_shape\x18\n \x03(\r\x12\x0f\n\x07weights\x18\x06 \x03(\x02\x12\x0e\n\x06\x62iases\x18\x07 \x03(\x02\x12\x14\n\x0ckernel_shape\x18\x0b \x03(\r\x12\x0e\n\x06stride\x18\x0c \x03(\r\x12\x0f\n\x07padding\x18\r \x03(\r\x12\x13\n\x08\x64ilation\x18\x10 \x01(\r:\x01\x31\x12\x1a\n\x0c\x61pply_col2im\x18\x0e \x01(\x08:\x04true\x12\x12\n\nlocal_size\x18\x0f \x01(\r\x12\x10\n\x05\x61lpha\x18\x13 \x01(\x02:\x01\x31\x12\x12\n\x04\x62\x65ta\x18\x14 \x01(\x02:\x04\x30.75\x12\x0f\n\x07pool_fn\x18\x18 \x01(\t\x12\x13\n\x0b\x63lass_names\x18\x15 \x03(\t\"d\n\x05Layer\x12\x0c\n\x04name\x18\x16 \x02(\t\x12\x0c\n\x04type\x18\x17 \x02(\t\x12#\n\x06params\x18\x02 \x02(\x0b\x32\x13.network.LayerParam\x12\x0c\n\x04prev\x18\x03 \x03(\t\x12\x0c\n\x04next\x18\x04 \x03(\t\"~\n\x07Network\x12\x0c\n\x04name\x18\x01 \x02(\t\x12\x12\n\nnum_layers\x18\x05 \x02(\r\x12\x1a\n\x0buse_threads\x18\x11 \x01(\x08:\x05\x66\x61lse\x12\x15\n\x07use_gpu\x18\x12 \x01(\x08:\x04true\x12\x1e\n\x06layers\x18\x08 \x03(\x0b\x32\x0e.network.Layer')
)




_LAYERPARAM = _descriptor.Descriptor(
  name='LayerParam',
  full_name='network.LayerParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='input_shape', full_name='network.LayerParam.input_shape', index=0,
      number=9, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='output_shape', full_name='network.LayerParam.output_shape', index=1,
      number=10, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='weights', full_name='network.LayerParam.weights', index=2,
      number=6, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='biases', full_name='network.LayerParam.biases', index=3,
      number=7, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='kernel_shape', full_name='network.LayerParam.kernel_shape', index=4,
      number=11, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stride', full_name='network.LayerParam.stride', index=5,
      number=12, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='padding', full_name='network.LayerParam.padding', index=6,
      number=13, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dilation', full_name='network.LayerParam.dilation', index=7,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='apply_col2im', full_name='network.LayerParam.apply_col2im', index=8,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='local_size', full_name='network.LayerParam.local_size', index=9,
      number=15, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='alpha', full_name='network.LayerParam.alpha', index=10,
      number=19, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(1),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='beta', full_name='network.LayerParam.beta', index=11,
      number=20, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.75),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pool_fn', full_name='network.LayerParam.pool_fn', index=12,
      number=24, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='class_names', full_name='network.LayerParam.class_names', index=13,
      number=21, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=315,
)


_LAYER = _descriptor.Descriptor(
  name='Layer',
  full_name='network.Layer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='network.Layer.name', index=0,
      number=22, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='network.Layer.type', index=1,
      number=23, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='network.Layer.params', index=2,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prev', full_name='network.Layer.prev', index=3,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='next', full_name='network.Layer.next', index=4,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=317,
  serialized_end=417,
)


_NETWORK = _descriptor.Descriptor(
  name='Network',
  full_name='network.Network',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='network.Network.name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_layers', full_name='network.Network.num_layers', index=1,
      number=5, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_threads', full_name='network.Network.use_threads', index=2,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='use_gpu', full_name='network.Network.use_gpu', index=3,
      number=18, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='layers', full_name='network.Network.layers', index=4,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=419,
  serialized_end=545,
)

_LAYER.fields_by_name['params'].message_type = _LAYERPARAM
_NETWORK.fields_by_name['layers'].message_type = _LAYER
DESCRIPTOR.message_types_by_name['LayerParam'] = _LAYERPARAM
DESCRIPTOR.message_types_by_name['Layer'] = _LAYER
DESCRIPTOR.message_types_by_name['Network'] = _NETWORK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LayerParam = _reflection.GeneratedProtocolMessageType('LayerParam', (_message.Message,), dict(
  DESCRIPTOR = _LAYERPARAM,
  __module__ = 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.LayerParam)
  ))
_sym_db.RegisterMessage(LayerParam)

Layer = _reflection.GeneratedProtocolMessageType('Layer', (_message.Message,), dict(
  DESCRIPTOR = _LAYER,
  __module__ = 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.Layer)
  ))
_sym_db.RegisterMessage(Layer)

Network = _reflection.GeneratedProtocolMessageType('Network', (_message.Message,), dict(
  DESCRIPTOR = _NETWORK,
  __module__ = 'network_pb2'
  # @@protoc_insertion_point(class_scope:network.Network)
  ))
_sym_db.RegisterMessage(Network)


# @@protoc_insertion_point(module_scope)
